spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://82.156.64.201:3306/test?autoreconnect=true"
    username: "walker"
    password: "walker"


mybatis:
  mapper-locations: classpath:mapper/*.xml


server:
  port: 6060




